#!/bin/sh

# /usr/bin/gnsu: gnsu's not su

PASSWORDTRIES=3

CMD="$@"

init() {
	export PATH="${PATH}:/sbin:/usr/sbin:/usr/local/sbin"

	# Translations only work with utf8 locales
	if [ ! `echo $LANG | grep -i utf` ]; then
		LANG=C
	fi

	# Gettext internationalization
	export TEXTDOMAIN="gnsu"
	export TEXTDOMAINDIR="/usr/share/locale"
	. gettext.sh

	export u=`whoami`

	export TRUE=/usr/bin/true

	export SUDO_ASKPASS=/usr/libexec/gnsu-helper
	export GNSU_ASKPASS=/usr/libexec/gnsu-askpass

	export COUNT=$PASSWORDTRIES
}

help() {
	cat <<- EOF
	Usage: $0 [SUDO OPTIONS] command [COMMAND ARGUMENTS]
	Run a command as another user through sudo
	
	OPTIONS:
	        -h, --help           Show this help
	EOF
}

storedpass() {
	sudo -n $TRUE 2> /dev/null
	return $?
}

askpass() {
	if [ $COUNT -lt $PASSWORDTRIES ]; then
		PERMISSION="-p"
	else
		PERMISSION=""
	fi
	GNSU_PASSWORD=$( $GNSU_ASKPASS \
		--title="$CMD" \
		--user="$u" \
		$PERMISSION \
		2> /dev/null)
	retval=$?
	if [ $retval -ne 0 ]; then
		exit 0
	fi
	export GNSU_PASSWORD
}

trypass() {
	sudo -A $TRUE 2> /dev/null
	return $?
}

execcommand() {
	sudo -A $CMD &
}

execcommandnopass() {
	sudo $CMD &
}

passwordloop() {
	if [ $COUNT -gt 0 ]; then
		askpass
		trypass
		retval=$?
		if [ $retval -eq 0 ]; then
			execcommand
			exit
		else
			let COUNT--
			passwordloop
		fi
	else
		exit 1
	fi
}

case $1 in
	-h | --help | "" )
	help
	exit
	;;
esac

init
storedpass
retval=$?
if [ $retval -eq 0 ]; then
	execcommandnopass
else
	passwordloop
fi

